name: Notion
description: Thoughts of me, Phil McClure
meta_description: "Notion, Blog of Phil McClure"

markdown: redcarpet
pygments: true
logo: false
paginate: 15
baseurl: /notion
permalink: /:year/:month/:day/:title

# Details for the RSS feed generator
url:            'blog url'
author:         'Phil McClure'
